import { createServer } from "https";
import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { parse } from "url";
import next from "next";
import httpProxy from "http-proxy";

// Accept self-signed certificates when proxying to the API backend
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");

const dev = process.env.NODE_ENV !== "production";
const hostname = process.env.HOSTNAME || "0.0.0.0";
const port = parseInt(process.env.PORT || "2742", 10);
const apiPort = parseInt(process.env.API_PORT || "2743", 10);
const apiTarget = process.env.API_URL || `https://127.0.0.1:${apiPort}`;

// Resolve TLS certificate: check env vars, then project root, then /var/lib/orion-complex
function findTlsFiles() {
  const candidates = [
    // Explicit env vars
    [process.env.TLS_CERT, process.env.TLS_KEY],
    // Project root (generated by Rust server)
    [resolve(projectRoot, "tls-cert.pem"), resolve(projectRoot, "tls-key.pem")],
    // Default data dir (where Rust server auto-generates them)
    ["/var/lib/orion-complex/tls-cert.pem", "/var/lib/orion-complex/tls-key.pem"],
  ];

  for (const [cert, key] of candidates) {
    if (cert && key && existsSync(cert) && existsSync(key)) {
      return { cert, key };
    }
  }

  console.error("Error: Could not find TLS certificate files.");
  console.error("Searched:", candidates.map(([c, k]) => `${c}, ${k}`).join("\n  "));
  process.exit(1);
}

const { cert: certFile, key: keyFile } = findTlsFiles();

const app = next({ dev, hostname, port, turbopack: false });
const handle = app.getRequestHandler();

const proxy = httpProxy.createProxyServer({
  target: apiTarget,
  ws: true,
  changeOrigin: true,
  secure: false,
});

proxy.on("error", (err, _req, res) => {
  console.error("Proxy error:", err.message);
  if (res.writeHead) {
    res.writeHead(502, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "backend unavailable" }));
  }
});

await app.prepare();

const httpsOptions = {
  key: readFileSync(keyFile),
  cert: readFileSync(certFile),
};

const server = createServer(httpsOptions, (req, res) => {
  const parsedUrl = parse(req.url, true);

  // Proxy /v1/* to the API backend
  if (parsedUrl.pathname?.startsWith("/v1/")) {
    proxy.web(req, res);
  } else {
    handle(req, res, parsedUrl);
  }
});

// Handle WebSocket upgrade for /v1/*/ws/*
// Must intercept before Next.js HMR handler gets it
server.on("upgrade", (req, socket, head) => {
  if (req.url?.startsWith("/v1/")) {
    console.log(`> WS upgrade: ${req.url}`);
    proxy.ws(req, socket, head);
  }
});

server.listen(port, hostname, () => {
  console.log(`> Ready on https://${hostname}:${port}`);
  console.log(`> API proxy -> ${apiTarget}`);
  console.log(`> TLS cert: ${certFile}`);
});
